spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/design?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
      username: root
      password: 123456
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      driver-class-name: com.mysql.jdbc.Driver

  thymeleaf:
    cache: false # 开发时关闭缓存,不然没法看到实时页面
    mode: LEGACYHTML5 # 用非严格的 HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
  aop:
    proxy-target-class: true

server:
  port: 8181

# MyBatis Config properties
mybatis:
  type-aliases-package: com.cn.jk.entity
  mapper-locations: classpath:mapper/*.xml
  # 驼峰
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
logging:
  level:
    org.caps.website: trace
  file: log/springboot.log
  pattern:
    file: .%d{yyyy-MM-dd} [%thread]  %-5level  %logger{50}  %msg%n
    console: .%d{yyyy-MM-dd} === [%thread] === %-5level === %logger{50} ==== %msg%n



